package main.sortBigFile.sort;

import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Holds all files which system generate.
 */
public class FileNamesHolder {

    private final Queue<String> files = new ArrayDeque<>();
    private volatile int size = 0;
    private AtomicInteger lastGen = new AtomicInteger();

    /**
     * Try acquire count files
     *
     * @param count count of files
     * @return list of acquired files
     */
    public List<String> get(int count) {
        while (true) {
            if (size >= count) {
                synchronized (this) {
                    if (size >= count) {
                        List<String> res = new ArrayList<>(count);
                        for (int i = 0; i < count; i++) {
                            res.add(files.remove());
                        }
                        size = size - count;
                        return res;
                    }
                }
            }
        }
    }

    /**
     * Pull new generated file
     *
     * @param inp name of new file
     */
    public void pull(String inp) {
        synchronized (this) {
            files.add(inp);
            size++;
        }
    }

    /**
     * Generate new unique name for file based on prefix
     *
     * @param name common file prefix
     * @return new unique name for file
     */
    public String getNewUniqueName(String name) {
        return name + this.lastGen.incrementAndGet();
    }

    /**
     * Get size of all files generated by system
     *
     * @return size of all files generated by system
     */
    public int getSize() {
        return size;
    }
}
